### ISSUE TITLE
Implementation of boolean query

### ISSUE THREAD

**Issue by aousadou** [askorama/orama#295]
I need to find 3000 elements in an index with 800 000 entries. Now, I do 3000 calls to search method to find elements. Each search call took approximately 150ms.

Implementation of boolean query may improve performances. Instead of doing 3000 calls, I want to do one query like that : 
`item1 OR item2 OR item3 ... OR itemN`

Meanwhile this kind of feature implemented, I will check if can do something similar directly by filtering content of `db.docs`

**Comment by rishi-raj-jain** [comment]
@micheleriva Did you get a look at this one? What do you think?

**Comment by micheleriva** [comment]
This feature has not been yet prioritized
