### ISSUE TITLE
Cannot create a string longer than 0x1fffffe8 characters when using data-persistence in server

### ISSUE THREAD

**Issue by imertz** [askorama/orama#554]
### Describe the bug

When trying to persist a large amount of data using the `persistToFile` function, Node.js throws an error: `Cannot create a string longer than 0x1fffffe8 characters`. This error is due to the V8 engine's limitation on string size.

### To Reproduce

1. Create a large dataset (larger than the V8 string size limit).
2. Try to persist this data using the `persistToFile` function.

### Expected behavior

The data should be successfully persisted to the file without any errors.

### Environment Info

```bash
OS: MacOS
Node: 20.7.0
Orama: 2.0.0 beta7
```

### Affected areas

Data Insertion

### Possible Solution:
Consider implementing a streaming approach to write the data to the file, which would avoid having to convert the entire Buffer to a string at once.

**Comment by micheleriva** [comment]
Thanks for opening this. @allevo we should rework the persistence plugin if we can reproduce this

**Comment by imertz** [comment]
> Hi @imertz ! Have you tried with a different format? For instance https://docs.oramasearch.com/open-source/plugins/plugin-data-persistence#persisting-the-database-to-disk-server-usage . Will that fit your case?

I'll try it out and come back to you.

**Comment by valstu** [comment]
Also noticed that you can write the msgpack encoded binary directly to file instead of turning it to hex before writing. This makes the msp file half the size.

**Comment by allevo** [comment]
Close this due to inactivity.

**Comment by djpimp2010** [comment]
This works both ways - I stumbled across this thread randomly after getting the same error while trying to read a log file into a nodejs script - the file happens to be around 850mb lol

So the easiest way to reproduce is to read or write an immense amount of data - like trying to run

`readFileSync(path, {encoding: "utf-8"});`

on an 850mb text file

I guarantee when trying to handle such a large string while writing to a file (persistToFile above) nodejs will encounter the same string length issue
