### ISSUE TITLE
Limit are not applied to string facet

### ISSUE THREAD

**Issue by davidsoderberg** [askorama/orama#561]
### Describe the bug

When I try to use following settings for a string facet:
```
{
      size: 175,
      limit: 200,
      order: 'DESC',
}
```
I only get 10 as the default limit is.

### To Reproduce

1. Create a orama instance with a string field with value that have over 10 different values.
2. try to get more than 10 face values for that field.
3. You will only get 10 even if asked for more

### Expected behavior

That I get the amount of facet strings I expected

### Environment Info

```bash
OS: MacOS 12.2.1
Node: 18.16.0
Orama: 2.0.0-beta.7
```

### Affected areas

Search

**Comment by micheleriva** [comment]
Thanks for opening this! We'll work on a fix

**Comment by SaraVieira** [comment]
Fixed by PR mentioned above
