### ISSUE TITLE
[plugin-data-persistence]: ERR_PACKAGE_PATH_NOT_EXPORTED, Issue with package import

### ISSUE THREAD

**Issue by KrishnaManohar1997** [askorama/orama#624]
### Describe the bug

When I'm trying to make use of `plugin-data-persistence` 
```
import { persistToFile } from '@orama/plugin-data-persistence';
```
I immediately face an error

```
    throw new Error(METHOD_MOVED('persistToFile'));
          ^

Error: Function persistToFile has been moved to the "/server" module. 

Import it via "import { persistToFile } from 'orama/plugin-data-persistence/server'". 
```

I then immediately updated the import to ```import { persistToFile } from 'orama/plugin-data-persistence/server'```
However facing the following import issue
<img width="1062" alt="image" src="https://github.com/oramasearch/orama/assets/20864237/7ab2b0af-55d7-4db8-8668-8d8448739f21">

I have then managed to remove the import error by changing the import path to 
```import { persistToFile } from '@orama/plugin-data-persistence/dist/server';```

This is leading to the following error

```
Error: ERR_PACKAGE_PATH_NOT_EXPORTED /Users/DevUser/myCode/nlp/node_modules/@orama/plugin-data-persistence/ ./dist/server /Users/DevUser/myCode/nlp/orama/databaseWrapper.ts
    at throwExportsNotFound ( /Users/DevUser/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:380:9)
    at packageExportsResolve ( /Users/DevUser/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:605:3)
    at packageResolve ( /Users/DevUser/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:746:14)
    at moduleResolve ( /Users/DevUser/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:798:18)
    at Object.defaultResolve ( /Users/DevUser/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:912:11)
```

I'm using the following command to execute my code
```node --trace-warnings --loader ts-node/esm driver.ts```

### To Reproduce

1. Installed Orama [Worked fine] (latest version)
2. Installed plugin-data-persistence latest version
3. Imported {persistToFile} package from `import { restoreFromFile } from '@orama/plugin-data-persistence/dist/server';`
4. Executed the `node --loader ts-node/esm driver.ts`
5. Faced with the error ```Error: ERR_PACKAGE_PATH_NOT_EXPORTE```

### Expected behavior

I expected the import to work normally, which is failing with importing the package component `persistToFile`

### Environment Info

```bash
OS: MacOs Sonoma 14.1.2
Node: v21.5.0
Orama: @orama/orama@2.0.3
Orama/plugin-data-persistence: @orama/plugin-data-persistence@2.0.3 [I've tried using old versions of the Plugin package]
```

### Affected areas

Initialization

**Comment by came** [comment]
Three weeks no response :/ I have the same issue.

**Comment by micheleriva** [comment]
Hi there, sorry for such a late reply. We're investigating

**Comment by micheleriva** [comment]
Quick question @came, @KrishnaManohar1997, are you using this in a CJS module or into an ESM one?

**Comment by djibe** [comment]
Import is `import { persist } from '@orama/plugin-data-persistence'` isn't it ?

**Comment by allevo** [comment]
It is hard to say without `tsconfig.json`.

I'm posting here codes that works.

`index.ts`
```ts
import { restoreFromFile } from '@orama/plugin-data-persistence/server';
console.log(restoreFromFile)
```

`tsconfig.json`
```ts
{
    "compilerOptions": {
        "module": "Node16",
        "moduleResolution": "Node16"
    }
}
```

run with `node --import tsx index.ts`.

Without further information, I'm closing this PR. Feel free to open a new one with a minimal reproducible example.
