### ISSUE TITLE
Cannot import from @orama/orama/components

### ISSUE THREAD

**Issue by came** [askorama/orama#657]
### Describe the bug

I try to create my own custom Index component as described here: https://docs.oramasearch.com/open-source/internals/components#index. Therefore, I need BM25, index and some other internal types / function. However, I cannot import them as described with 

```typescript
import { index as defaultIndex } from '@orama/orama/components'
``` 

Look like it is just not exported anymore :/

BR, Carsten

### To Reproduce

Just try to import an you will get the ts error:

Cannot find module '@orama/orama/components' or its corresponding type declarations.ts(2307)
⚠ Error (TS2307)  | 
Cannot find module 
 or its corresponding type declarations.

### Expected behavior

I would expect to import from '@orama/orama/components'

### Environment Info

```bash
OS: MacOS Version 14.1.1 (23B81)
Node: v20.0.0
Orama: ^2.0.9
```

### Affected areas

Initialization

### Additional context

I can import the defaultIndex like the following, but I cannot get types like this. e.g. Index

```typescript
import { components } from '@orama/orama'
const { getDocumentIndexId, index: defaultIndex, internalDocumentIDStore, documentsStore} = components
``` 

I looked into the source code, but I could not see an error.

**Comment by micheleriva** [comment]
@came we're on it

**Comment by micheleriva** [comment]
quick question, are you using Orama in TypeScript via ESM or via CJS?

**Comment by came** [comment]
Thank you 👍  I'm importing Orama as ESM
