### ISSUE TITLE
plugin-match-highlight does not work with array field

### ISSUE THREAD

**Issue by matijagaspar** [askorama/orama#669]
### Describe the bug

The plugin ignores array fields in the schema, so matches found inside string arrays do not list highlight positions

### To Reproduce

```js
import { create, insert } from '@orama/orama'
import { afterInsert as highlightAfterInsert, searchWithHighlight } from '@orama/plugin-match-highlight'
const db = await create({
  schema: {
    arrayToSearch: 'string[]'
  },
  plugins: [
    {
      name: 'highlight',
      afterInsert: highlightAfterInsert
    }
  ]
})

await insert(db, { arrayToSearch: ['hello world', 'world hello'] })

const results = await searchWithHighlight(db, {
  term: 'hello'
})
```

Results hits.positions being `{}`:

### Expected behavior

`positions` object in the hit to not be empty.

### Environment Info

```bash
OS: Ubuntu 22.04.4 LTS
Node: v18.12.1
Orama: 2.0.11
```

### Affected areas

Search

**Comment by jblyberg** [comment]
You should submit your change as a pull request. I'm interested in this functionality as well.

**Comment by jblyberg** [comment]
Also noticed that the result doesn't filter array strings that don't have a hit. This is kind of important when building search objects that need to query relations.

**Comment by micheleriva** [comment]
Hi folks,
I have an update on this. We're gonna deprecate this plugin in favor of https://www.npmjs.com/package/@orama/highlight. This allows more lightweight and faster indexes, I highly recommend using it.
