### ISSUE TITLE
Keyboard navigation with @orama/searchbox and vitepress

### ISSUE THREAD

**Issue by stafyniaksacha** [askorama/orama#691]
### Describe the bug

When using native keyboard navigation, multiples issues occurs:

1. <kbd>ctrl+k</kbd>: does not prevent default browser behavior, modal is open, but focus is given to browser address bar instead of the modal search input
2. <kbd>tab</kbd> / <kbd>shift+tab</kbd>: when in search modal with results, using default shortcuts to focus next element does not focus element that have click handler, so we can't hit <kbd>enter</kbd> to select the result (<kbd>↓</kbd> / <kbd>↑</kbd> works)

### To Reproduce

Go to https://docs.askorama.ai/

### Affected areas

Search

**Comment by micheleriva** [comment]
Hi @stafyniaksacha, thanks for opening this. We're currently reworking the searchbox, let me tag my colleagues who are working on this to ensure that this behavior is fixed.

cc. @g-francesca, @SaraVieira

**Comment by FlorianRappl** [comment]
Any news on this? Is this something that can be contributed via a PR?

**Comment by g-francesca** [comment]
Hi @FlorianRappl,
we encourage you to use the newly updated searchbox component, please refer to [this doc](https://docs.orama.com/cloud/ui-components/search-box) here. Please feel free to ping us if you still have issues with keyboard navigation

**Comment by FlorianRappl** [comment]
Hm so how would this work in Vitepress @g-francesca ?

I'm sorry if I wasn't really specific beforehand, but the package I'm using is [@orama/plugin-vitepress](https://www.npmjs.com/package/@orama/plugin-vitepress). As of today, the v2 is broken as per OP and the v3 (preview) is not working at all for me (using VitePress v1, i.e., latest stable version).
