### ISSUE TITLE
Cannot read properties of undefined ( reading: 'title') in Vitepress

### ISSUE THREAD

**Issue by DominusKelvin** [askorama/orama#701]
### Describe the bug

When I use the Orama plugin for Vitepress on [Sailscasts Docs](https://docs.sailscasts.com) I get an error on the console that `Cannot read properties of undefined ( reading: 'title')`

### To Reproduce

1. Initialize the Orama plugin for Vitepress.
2. Make a search

### Expected behavior

I expected for Orama to not error out for pages that don't have title

### Environment Info

```bash
Node: v21.7.1
@orama/plugin-vitepress: 2.0.16
```

### Affected areas

Search

### Additional context

![CleanShot 2024-04-17 at 17 57 40@2x](https://github.com/askorama/orama/assets/24433274/4d764793-c104-43d7-bf2d-814c07356ab3)

**Comment by SaraVieira** [comment]
Hey!

Sorry about that, I just made a PR that will fix this error and it will be available in the next version

**Comment by DominusKelvin** [comment]
Thanks @SaraVieira and FYI, I think the problem still persist as I still receive the error even after upgrading to 2.0.18

![CleanShot 2024-05-20 at 09 12 24@2x](https://github.com/askorama/orama/assets/24433274/aa135068-6441-4694-b965-a51a7043e28b)

**Comment by SaraVieira** [comment]
There hasn't been a new one after my PR, let me ask today for a new release
