### ISSUE TITLE
Plugin for Docusaurus not working + gets confusing on 2nd attempt of serve

### ISSUE THREAD

**Issue by tfulanchan** [askorama/orama#704]
### Describe the bug

I am deploying Orama for a Docusaurus application. 

Before Orama is deployed, the "Usage" section used to display code for docusaurus.config.js and "Set the API key" only as shown in the [Docs](https://docs.askorama.ai/cloud/data-sources/native-integrations/docusaurus) as of this moment. 
![useBeforeDeploy](https://github.com/askorama/orama/assets/60479975/7a9d0499-d940-4b43-9eb2-52930822880a)

Once Orama was deployed and a Docusaurus website is served locally, the "Usage" section changed completely:
"API endpoint" pops up on the top, "API Integration" appears and configurations for docusaurus.config.js disappeared.
![usageAfterDeployed](https://github.com/askorama/orama/assets/60479975/27a289bb-9cd6-46e7-b482-a48d0fed1076)

The Console is showing the following errors when the project is built and served for another time.
![oramaFailure](https://github.com/askorama/orama/assets/60479975/cdc92339-3da3-48b9-820d-9dc1d5c20879)

It seems I need an API endpoint after Orama is deployed but the documentation does not describe how to configure it for Docusaurus completely, not to mention the code blog displayed in the "Usage" section. Very confusing, the Docs needs to clarify the integration of Orama Cloud for Docusaurus specifically.

### To Reproduce

1. Initiate a Docusaurus project and install the Orama plugin
2. Create an index as instructed in the [documentation](https://docs.askorama.ai/cloud/data-sources/native-integrations/docusaurus)
3. Add `@orama/plugin-docusaurus-v3` to Docusaurus list of plugins in `docusaurus.config.js`
4. Build the Docusaurus project and serve for the 1st time
5. Stop the serve and serve for 2nd time

### Expected behavior

I expect Orama plugin working fine in 2nd attempt but the Orama search component on the top is no longer responding in 2nd attempt of `build` and `serve`

### Environment Info

```bash
OS: Windows 10
Node: >=18.0
Docusaurus: 3.2.1
@orama/plugin-docusaurus-v3: 2.0.16
@oramacloud/client: ^1.0.14
```

### Affected areas

Search

**Comment by micheleriva** [comment]
Hi there, @raiindev is looking into that!

**Comment by raiindev** [comment]
Hey @tfulanchan, we updated the docusaurus flow on the dashboard to make it clearer.
Let me know if it helps!
