### ISSUE TITLE
Feature request: Multiple vector properties to enable multi-modal search

### ISSUE THREAD

**Issue by nicolastoulemont** [askorama/orama#711]
Add the possibility of having multiple (at least 2) vector properties to search through to facilitate multi-modal search, for example: image + semantic.

This kind of multi-modal search is currently only doable via multiple indexes and sequential queries to the different DBs which is slower.

This multi-modal search will probably mostly be used in an e-commerce context but one could imagine it being useful in RAG applications as well

**Comment by micheleriva** [comment]
Hi @nicolastoulemont,
yes you can have multiple vector properties: https://docs.askorama.ai/open-source/usage/search/vector-search#performing-vector-search

**Comment by nicolastoulemont** [comment]
Thanks for the answer @micheleriva !
It looks like I misinterpreted the "only search through one vector property at a time" and wrongly assumed it also meant only having one vector prop per DB, my bad !

**Comment by micheleriva** [comment]
@nicolastoulemont I should probably phrase it better, thanks for noticing!
