### ISSUE TITLE
Memory usage: all strings seem to be duplicated

### ISSUE THREAD

**Issue by masylum** [askorama/orama#735]
### Describe the bug

I have no idea if it's a bug, feel free to dismiss otherwise.
I'm profiling an app I'm building with orama, and I see that all the strings are duplicated, but one is in lower case and the other is not.

![CleanShot 2024-06-16 at 23 53 09](https://github.com/askorama/orama/assets/28248/ba423ebd-e3c9-4ad8-b96c-3a7e8551adeb)

if it helps, those are the retainer objects of two of the strings:
![CleanShot 2024-06-16 at 23 55 14](https://github.com/askorama/orama/assets/28248/e7bb9932-8daa-4917-9315-3f8f95a7b19e)
![CleanShot 2024-06-16 at 23 55 45](https://github.com/askorama/orama/assets/28248/8de1d3d8-1dc4-4ff1-a086-173a91e6ca2a)

### To Reproduce

Open the heap profiler in chrome and once you have the snapshot, check the strings.

### Expected behavior

Only one copy of the string being in memory (ideally, no idea if there is a limitation)

### Environment Info

```bash
Chrome 125
```

### Affected areas

Initialization, Environment/OS

### Additional context

thanks for orama, is fantastic!

**Comment by micheleriva** [comment]
We're aware of this situation and we're actively working on a fix that will be released in Orama `v3.0.0`. Please keep following us on Twitter or here on GitHub to get notified when we'll announce the fix!

**Comment by masylum** [comment]
awesome!
