### ISSUE TITLE
Sync/Async APIs

### ISSUE THREAD

**Issue by masylum** [askorama/orama#736]
### Problem Description

According to my profiling, most of the time spent on ingesting documents is spent on "run microtask". Particularly the `insertScalarBuilder` is specially hot, and it has a lot of faux async/await that is actually doing sync work by default. I understand this is because you want to have an async API for people to provide their storage, but it makes the default in-memory much slower.

### Proposed Solution

Perhaps an option would be to have 2 APIs, a sync and an async one? This is yet another example of https://journal.stuffwithstuff.com/2015/02/01/what-color-is-your-function, which sucks, but I don't make the rules.

### Additional Context

![CleanShot 2024-06-17 at 11 29 57](https://github.com/askorama/orama/assets/28248/754cc462-eea6-4b29-ab7b-ce85bab4dcd8)

**Comment by micheleriva** [comment]
Hi @masylum, we turned all APIs to sync with Orama v3.0.0-rc2.

**Comment by masylum** [comment]
This is awesome! will try and check whether this fixes performance
