### ISSUE TITLE
Docusaurus V3 plugin - Add fragments to header (H2, H3, ...) links

### ISSUE THREAD

**Issue by madlitz** [askorama/orama#751]
### Problem Description

Docusaurus automatically adds id props to all header tags except for H1. Currently the plugin picks up each header as a section but only puts the file path in the url without a fragment.

### Proposed Solution

The plugin could be modified to automatically add a fragment to all header sections (except for H1). The fragment is calculated from the header text:

`Before you start` -> `#before-you-start`

Also special characters are removed:

`1. Setup` -> `#1-setup`

### Additional Context

The function that needs to be modified is this one:

https://github.com/askorama/orama/blob/main/packages/plugin-docusaurus-v3/src/index.ts#L251-L274

If there are no objections to the proposed solution I am happy to create a PR.

**Comment by madlitz** [comment]
Need to support explicit ids also: [https://docusaurus.io/docs/markdown-features/toc](https://docusaurus.io/docs/markdown-features/toc)

**Comment by madlitz** [comment]
Here is my first attempt: 456fb63fa4bba79972298ff2aecccfd8b138a286

It adds the fragments but for some reason when you click on the search result it doesn't jump down to the fragment id.

**Comment by madlitz** [comment]
Okay after more investigation it looks like when using `docusaurus start` it works in browser as expected with no network calls, however when using `docusaurus serve` it starts trying to hit the remote server again. Most likely a configuration issue somewhere.

**Comment by micheleriva** [comment]
That should be fixed by #755
