### ISSUE TITLE
Console spammed with `Rebalancing tree after XXX inserts...`

### ISSUE THREAD

**Issue by gustavopch** [askorama/orama#774]
https://github.com/askorama/orama/blob/0c2c76ca3c9f23570f3162a4b12930e88f35c1fb/packages/orama/src/trees/avl.ts#L230
If I insert thousands of items with `insertMultiple`, Orama generates thousands of these logs. Consider:
- Removing the log, or
- Logging fewer times, or
- Disabling the log when `NODE_ENV === 'production'`

**Comment by micheleriva** [comment]
Fixed with #777, thanks for spotting this 🙏
